export const CROUSEL_LIST = [
  {
    type: "carouselElement",
    subtype: "image",
    data: {
      bannerId: 635529,
      creativeId: "rng/md/carousel/production/pneknawbadtvceqzwiep",
      type: "restaurantCollectionV2",
      link: "49301",
      cityId: 0,
      restaurantUuid: "",
      restaurantParentId: "0",
      thirdPartyVendor: "",
      thirdPartyAddress: false,
    },
  },
  {
    type: "carouselElement",
    subtype: "image",
    data: {
      bannerId: 619141,
      creativeId: "rng/md/carousel/production/zpkkdkmvlj5cuvqbc50t",
      type: "restaurantCollectionV2",
      link: "56413",
      cityId: 0,
      restaurantUuid: "",
      restaurantParentId: "0",
      thirdPartyVendor: "",
      thirdPartyAddress: false,
    },
  },
  {
    type: "carouselElement",
    subtype: "image",
    data: {
      bannerId: 619143,
      creativeId: "rng/md/carousel/production/lzkjv3sxwwjkzg0vxpvt",
      type: "restaurantCollectionV2",
      link: "56422",
      cityId: 0,
      restaurantUuid: "",
      restaurantParentId: "0",
      thirdPartyVendor: "",
      thirdPartyAddress: false,
    },
  },
  {
    type: "carouselElement",
    subtype: "image",
    data: {
      bannerId: 619142,
      creativeId: "rng/md/carousel/production/tgnvusbs3fnzz7xupeno",
      type: "restaurantCollectionV2",
      link: "56417",
      cityId: 0,
      restaurantUuid: "",
      restaurantParentId: "0",
      thirdPartyVendor: "",
      thirdPartyAddress: false,
    },
  },
  {
    type: "carouselElement",
    subtype: "image",
    data: {
      bannerId: 619145,
      creativeId: "rng/md/carousel/production/nhubtkw7dukg3ukcmpam",
      type: "restaurantCollectionV2",
      link: "56414",
      cityId: 0,
      restaurantUuid: "",
      restaurantParentId: "0",
      thirdPartyVendor: "",
      thirdPartyAddress: false,
    },
  },
  {
    type: "carouselElement",
    subtype: "image",
    data: {
      bannerId: 607188,
      creativeId: "rng/md/carousel/production/oxe97jexxbnxqtbhg2zo",
      type: "restaurantCollectionV2",
      link: "11740",
      cityId: 0,
      restaurantUuid: "",
      restaurantParentId: "0",
      thirdPartyVendor: "",
      thirdPartyAddress: false,
    },
  },
];

export const CARD_LIST = [
  {
    cardType: "seeAllRestaurants",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "seeAllRestaurants",
      data: {
        title: "SEE ALL",
        totalOpenRestaurants: 1469,
        cards: [
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "684224",
              name: "Bodypower Cafe",
              uuid: "50065bf7-2398-4596-a835-35fa42e221c7",
              city: "1",
              area: "Indiranagar",
              totalRatingsString: "100+ ratings",
              cloudinaryImageId: "b8ea636736c03ca4ce34676e01515337",
              cuisines: ["Indian", "South Indian", "Healthy Food", "Beverages"],
              tags: [],
              costForTwo: 45000,
              costForTwoString: "₹450 FOR TWO",
              deliveryTime: 36,
              minDeliveryTime: 36,
              maxDeliveryTime: 36,
              slaString: "36 MINS",
              lastMileTravel: 5.800000190734863,
              slugs: {
                restaurant: "bodypower-cafe-indiranagar-indiranagar",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "21, Chinmaya Mission Hospital Rd, near Manyavar, Indira Nagar II Stage, Hoysala Nagar, Indiranagar, Bengaluru, Karnataka 560038, India",
              locality: "Hoysala Nagar",
              parentId: 280671,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5200,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5200,
                message: "",
                title: "Delivery Charge",
                amount: "5200",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=6893111~p=1~eid=00000188-9adc-94e8-08b7-a56b004c0121",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "5.8 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹150 OFF",
                subHeader: "ABOVE ₹249",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "684224",
                deliveryTime: 36,
                minDeliveryTime: 36,
                maxDeliveryTime: 36,
                lastMileTravel: 5.800000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.2",
              totalRatings: 100,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "80517",
              name: "Savoury Restaurant",
              uuid: "75fd0f34-da99-457f-b8ec-f6c9dcc6bc4c",
              city: "1",
              area: "Frazer Town",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "6b38d5679a48a299242c364df3975f2f",
              cuisines: [
                "Arabian",
                "Indian",
                "Chinese",
                "Tandoor",
                "Biryani",
                "Seafood",
                "Kerala",
              ],
              tags: [],
              costForTwo: 45000,
              costForTwoString: "₹450 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 4.900000095367432,
              slugs: {
                restaurant: "savoury-restaurant-frazer-town-frazer-town",
                city: "bangalore",
              },
              cityState: "1",
              address: "No:27, Mosque Road, Frazer town, Bangalore - 560005",
              locality: "Mosque Road",
              parentId: 179209,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3900,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3900,
                message: "",
                title: "Delivery Charge",
                amount: "3900",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "4.9 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "20% OFF",
                subHeader: "UPTO ₹50",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "80517",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 4.900000095367432,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.3",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "709752",
              name: "Melting Cheese",
              uuid: "04574ddf-e31c-43be-a382-e30d549d0ed8",
              city: "1",
              area: "Basavanagudi",
              totalRatingsString: "Too Few Ratings",
              cloudinaryImageId: "cfe5a6b2c186e42811f595e7ebfd7331",
              cuisines: ["Pizzas", "Fast Food"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 32,
              minDeliveryTime: 32,
              maxDeliveryTime: 32,
              slaString: "32 MINS",
              lastMileTravel: 3,
              slugs: {
                restaurant: "melting-cheese-basavanagudi-basavanagudi-2",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "12, Rangaswamy Temple St, opp. Chikkaballapura Pete Market, Anchepet, Chickpet, Bengaluru, Karnataka 560053, India",
              locality: "Rangaswamy Temple St",
              parentId: 135174,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3300,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "3 kms",
              hasSurge: false,
              sla: {
                restaurantId: "709752",
                deliveryTime: 32,
                minDeliveryTime: 32,
                maxDeliveryTime: 32,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "--",
              totalRatings: 0,
              new: true,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "336364",
              name: "Third Wave Coffee",
              uuid: "0beefd12-749b-4550-a3b6-bea048256bb1",
              city: "1",
              area: "Ashok Nagar",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "0dca660dbdf2e04f9b861c4426ffd41e",
              cuisines: ["Beverages", "Bakery", "Continental"],
              tags: [],
              costForTwo: 40000,
              costForTwoString: "₹400 FOR TWO",
              deliveryTime: 25,
              minDeliveryTime: 25,
              maxDeliveryTime: 25,
              slaString: "25 MINS",
              lastMileTravel: 1.7999999523162842,
              slugs: {
                restaurant:
                  "third-wave-coffee-roasters-central-bangalore-central-bangalore",
                city: "bangalore",
              },
              cityState: "1",
              address:
                'Sy No.52/2, "Sujay\'s Pride", Church Street, Bangalore, B.B.M.P East, Karnataka-560001',
              locality: "Church Street",
              parentId: 274773,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=6948789~p=31~eid=00000188-9adc-94e8-08b7-a575004c1f03",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "1.7 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "336364",
                deliveryTime: 25,
                minDeliveryTime: 25,
                maxDeliveryTime: 25,
                lastMileTravel: 1.7999999523162842,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.5",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "435405",
              name: "Chaayos Chai+Snacks=Relax",
              uuid: "83f35f21-d3c1-42d1-847a-7fe2d1567f15",
              city: "1",
              area: "Cunningham Road",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "2beebd3688e63e027ee8a11c1c8a72c8",
              cuisines: [
                "Bakery",
                "Beverages",
                "Chaat",
                "Desserts",
                "Home Food",
                "Italian",
                "Maharashtrian",
                "Snacks",
                "Street Food",
                "Sweets",
              ],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 31,
              minDeliveryTime: 31,
              maxDeliveryTime: 31,
              slaString: "31 MINS",
              lastMileTravel: 3,
              slugs: {
                restaurant:
                  "chaayos-meri-wali-chai-cunningham-road-central-bangalore",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "Shop No. 15, 22, 23 and 24, Ground Floor, Unit No. 02, HM Geneva House, #14 Cunningham Road, Vasanth Nagar, Shivajinagara, B.B.M.P East, Karnataka-560052",
              locality: "Vasanth Nagar",
              parentId: 281782,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3300,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "3 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "50% OFF",
                subHeader: "UPTO ₹100",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "435405",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 3,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.4",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "204552",
              name: "Adithya Tiffin Centre",
              uuid: "6f70b5fd-90b6-484f-abf9-e0b6b91e0028",
              city: "1",
              area: "Shanti Nagar",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "q7sy5nrq20td2tnlebye",
              cuisines: ["North Indian"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 28,
              minDeliveryTime: 28,
              maxDeliveryTime: 28,
              slaString: "28 MINS",
              lastMileTravel: 2.5999999046325684,
              slugs: {
                restaurant: "adithya-tiffin-centre-shantinagar-shantinagar",
                city: "bangalore",
              },
              cityState: "1",
              address: "7/1, B Street, Shanthinagar, Bangalore - 560027",
              locality: "Anugraha Layout",
              parentId: 27177,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "2.5 kms",
              hasSurge: false,
              sla: {
                restaurantId: "204552",
                deliveryTime: 28,
                minDeliveryTime: 28,
                maxDeliveryTime: 28,
                lastMileTravel: 2.5999999046325684,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.7",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "607431",
              name: "Samosa Party",
              uuid: "3bbdeb8e-230b-4061-abe5-56c30d5f86f7",
              city: "1",
              area: "Koramangala",
              totalRatingsString: "100+ ratings",
              cloudinaryImageId: "ahwtmr2oa0xwaujup9wp",
              cuisines: [
                "Fast Food",
                "Snacks",
                "Beverages",
                "Chaat",
                "North Indian",
                "Street Food",
                "Sweets",
                "Desserts",
                "Punjabi",
                "Bakery",
              ],
              tags: [],
              costForTwo: 15000,
              costForTwoString: "₹150 FOR TWO",
              deliveryTime: 38,
              minDeliveryTime: 38,
              maxDeliveryTime: 38,
              slaString: "38 MINS",
              lastMileTravel: 6.5,
              slugs: {
                restaurant: "samosa-party-koramangala-koramangala-2",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "SAMOSAPARTY FOODS PRIVATE LIMITED FORUM MALL, MUNICIPAL NO.21, HOSUR ROAD, LAKKASANDRA WARD NO.06, (EARLIER FORMING PART OF SY.151, KORAMANGALA VILLAGE AND SY NO.67/2, 67/3, 67/4 & 67/5 OF AUDIGODI VI",
              locality: "Koramangala",
              parentId: 6364,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5800,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5800,
                message: "",
                title: "Delivery Charge",
                amount: "5800",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=6948758~p=7~eid=00000188-9adc-94e8-08b7-a56d004c0742",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6.5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "ABOVE ₹1000",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "607431",
                deliveryTime: 38,
                minDeliveryTime: 38,
                maxDeliveryTime: 38,
                lastMileTravel: 6.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.3",
              totalRatings: 100,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "69876",
              name: "Subway",
              uuid: "d1a0e6e6-575c-4453-9f78-d298026b0e64",
              city: "1",
              area: "Ashok Nagar",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "0bf19a82b109b40c2f5c56d00f071a33",
              cuisines: [
                "Fast Food",
                "Salads",
                "Snacks",
                "Desserts",
                "Beverages",
              ],
              tags: [],
              costForTwo: 35000,
              costForTwoString: "₹350 FOR TWO",
              deliveryTime: 25,
              minDeliveryTime: 25,
              maxDeliveryTime: 25,
              slaString: "25 MINS",
              lastMileTravel: 0.20000000298023224,
              slugs: {
                restaurant: "subway-central-bangalore1-central-bangalore",
                city: "bangalore",
              },
              cityState: "1",
              address: "Ubcity 2nd level Vital mallya Road Bangalore",
              locality: "UB City",
              parentId: 2,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "0.2 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "30% OFF",
                subHeader: "UPTO ₹75",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "69876",
                deliveryTime: 25,
                minDeliveryTime: 25,
                maxDeliveryTime: 25,
                lastMileTravel: 0.20000000298023224,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.1",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "637141",
              name: "The Home Bakery",
              uuid: "4885cb81-ca9f-44ee-a4aa-534dfe7fe784",
              city: "1",
              area: "Frazer Town",
              totalRatingsString: "20+ ratings",
              cloudinaryImageId: "igyqxtmnvpnbtdisfi0e",
              cuisines: ["Bakery", "Desserts"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 31,
              minDeliveryTime: 31,
              maxDeliveryTime: 31,
              slaString: "31 MINS",
              lastMileTravel: 4.699999809265137,
              slugs: {
                restaurant: "the-home-bakery-frazer-town-frazer-town",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "5/1, L1-05 Ground Floor, Assaye Rd, Halasuru, Sindhi Colony, Pulikeshi Nagar, Bengaluru, Karnataka 560042, India",
              locality: "Assaye Rd",
              parentId: 209607,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3900,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3900,
                message: "",
                title: "Delivery Charge",
                amount: "3900",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 1,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "4.6 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "40% OFF",
                subHeader: "UPTO ₹80",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "637141",
                deliveryTime: 31,
                minDeliveryTime: 31,
                maxDeliveryTime: 31,
                lastMileTravel: 4.699999809265137,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.3",
              totalRatings: 20,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "3062",
              name: "Rolls On Wheels",
              uuid: "dd0acb18-9dca-431b-9c9a-0410d6e501d1",
              city: "1",
              area: "ST MARKS ROAD",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "nvoxfgrzkhay0v5fzwxx",
              cuisines: ["Snacks"],
              tags: [],
              costForTwo: 30000,
              costForTwoString: "₹300 FOR TWO",
              deliveryTime: 18,
              minDeliveryTime: 18,
              maxDeliveryTime: 18,
              slaString: "18 MINS",
              lastMileTravel: 0.800000011920929,
              slugs: {
                restaurant: "rolls-on-wheels-banashankari-2",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "VASAVI COMPLEX, NO.17, ST MARKS ROAD,BANAGLORE, Shanthinagara , B.B.M.P East",
              locality: "Shanthinagara",
              parentId: 784,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=7028362~p=10~eid=00000188-9adc-94e8-08b7-a56e004c0a75",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "0.8 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "25% OFF",
                subHeader: "UPTO ₹65",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "3062",
                deliveryTime: 18,
                minDeliveryTime: 18,
                maxDeliveryTime: 18,
                lastMileTravel: 0.800000011920929,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.3",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "424609",
              name: "Bikaner Sweets",
              uuid: "8db1be0e-9220-4408-9a40-7f534645a307",
              city: "1",
              area: "Jayanagar",
              totalRatingsString: "100+ ratings",
              cloudinaryImageId: "okjfoyr1ppofcsqvqsyz",
              cuisines: ["Sweets"],
              tags: [],
              costForTwo: 9900,
              costForTwoString: "₹99 FOR TWO",
              deliveryTime: 35,
              minDeliveryTime: 35,
              maxDeliveryTime: 35,
              slaString: "35 MINS",
              lastMileTravel: 6.300000190734863,
              slugs: {
                restaurant: "bikaner-sweets-jayanagar-jayanagar",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "530, 11th Main Rd, near GRT Jewellers, 4th T Block East, 4th Block, Jayanagar, Bengaluru, Karnataka 560011, India",
              locality: "4th T Block",
              parentId: 2654,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5800,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5800,
                message: "",
                title: "Delivery Charge",
                amount: "5800",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 1,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6.3 kms",
              hasSurge: false,
              sla: {
                restaurantId: "424609",
                deliveryTime: 35,
                minDeliveryTime: 35,
                maxDeliveryTime: 35,
                lastMileTravel: 6.300000190734863,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.1",
              totalRatings: 100,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "39064",
              name: "SLV Delite",
              uuid: "4416a832-101f-48b0-87b6-e7b6c7151515",
              city: "1",
              area: "Malleshwaram",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "yhw2zwj8ablggrbrbveo",
              cuisines: ["Chinese", "North Indian", "South Indian"],
              tags: [],
              costForTwo: 35000,
              costForTwoString: "₹350 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 3.5,
              slugs: {
                restaurant: "slv-delite-majestic-majestic",
                city: "bangalore",
              },
              cityState: "1",
              address: "No 32/33 1st main road Gandhinagar bangalore 560009",
              locality: "Gandhi Nagar",
              parentId: 189520,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 3300,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 3300,
                message: "",
                title: "Delivery Charge",
                amount: "3300",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "3.5 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "10% OFF",
                subHeader: "UPTO ₹40",
                discountTag: "",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "39064",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 3.5,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "3.9",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "29063",
              name: "Misu",
              uuid: "e48dab10-bade-4287-b076-ac413a5bae51",
              city: "1",
              area: "St Marks Road",
              totalRatingsString: "1000+ ratings",
              cloudinaryImageId: "lx0tpfgsbqygafwh30wh",
              cuisines: [
                "Asian",
                "Chinese",
                "Vietnamese",
                "Malaysian",
                "Sushi",
                "Singaporean",
                "Desserts",
              ],
              tags: [],
              costForTwo: 130000,
              costForTwoString: "₹1300 FOR TWO",
              deliveryTime: 26,
              minDeliveryTime: 26,
              maxDeliveryTime: 26,
              slaString: "26 MINS",
              lastMileTravel: 0.699999988079071,
              slugs: {
                restaurant: "misu-st-marks-road-central-bangalore",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "4th Floor, Halcyon Complex, Saint Marks Road, Ashok Nagar, Bengaluru, Karnataka 560001",
              locality: "Ashok Nagar",
              parentId: 7415,
              unserviceable: false,
              veg: false,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              ribbon: [
                {
                  type: "PROMOTED",
                },
              ],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 2700,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 2700,
                message: "",
                title: "Delivery Charge",
                amount: "2700",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID:
                "cid=6918674~p=13~eid=00000188-9adc-94e8-08b7-a56f004c0d58",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "0.6 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹150 OFF",
                subHeader: "ABOVE ₹999",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "29063",
                deliveryTime: 26,
                minDeliveryTime: 26,
                maxDeliveryTime: 26,
                lastMileTravel: 0.699999988079071,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: true,
              avgRating: "4.4",
              totalRatings: 1000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "296218",
              name: "Hotel Dwarka",
              uuid: "5d89718f-5fdf-4a78-b6f8-f8ccc9b7b6bf",
              city: "1",
              area: "Basavanagudi",
              totalRatingsString: "10000+ ratings",
              cloudinaryImageId: "aqndq5znlt3iifroa1mt",
              cuisines: ["South Indian"],
              tags: [],
              costForTwo: 20000,
              costForTwoString: "₹200 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 6.099999904632568,
              slugs: {
                restaurant: "hotel-dwarka-basavanagudi-basavanagudi",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "7th Cross Rd, NR Colony, Basavanagudi, Bengaluru, Karnataka  560004",
              locality: "NR Colony",
              parentId: 21130,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5800,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5800,
                message: "",
                title: "Delivery Charge",
                amount: "5800",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 1,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6 kms",
              hasSurge: false,
              sla: {
                restaurantId: "296218",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 6.099999904632568,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "IT_IS_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.5",
              totalRatings: 10000,
              new: false,
            },
            subtype: "basic",
          },
          {
            type: "restaurant",
            data: {
              type: "F",
              id: "534235",
              name: "Cheesecake & Co.",
              uuid: "6da20d08-e548-4654-9e27-616761693e3d",
              city: "1",
              area: "Koramangala",
              totalRatingsString: "500+ ratings",
              cloudinaryImageId: "40b0a201eadbec469c2f9a06d5e7c722",
              cuisines: ["Bakery"],
              tags: [],
              costForTwo: 25000,
              costForTwoString: "₹250 FOR TWO",
              deliveryTime: 33,
              minDeliveryTime: 33,
              maxDeliveryTime: 33,
              slaString: "33 MINS",
              lastMileTravel: 6.099999904632568,
              slugs: {
                restaurant: "cheesecake-and-co-koramangala-koramangala",
                city: "bangalore",
              },
              cityState: "1",
              address:
                "PROPERTY NO. 9/C, 3RD MAIN OPP,  KORAMANGALA POLICE STATION  BANGALORE, , Bangalore South, Bangalore  Urban, Karnataka",
              locality: "6th Block",
              parentId: 387417,
              unserviceable: false,
              veg: true,
              select: false,
              favorite: false,
              tradeCampaignHeaders: [],
              chain: [],
              feeDetails: {
                fees: [
                  {
                    name: "distance",
                    fee: 5800,
                    message: "",
                  },
                  {
                    name: "time",
                    fee: 0,
                    message: "",
                  },
                  {
                    name: "special",
                    fee: 0,
                    message: "",
                  },
                ],
                totalFees: 5800,
                message: "",
                title: "Delivery Charge",
                amount: "5800",
                icon: "",
              },
              availability: {
                opened: true,
                nextOpenMessage: "",
                nextCloseMessage: "",
              },
              longDistanceEnabled: 0,
              rainMode: "NONE",
              thirdPartyAddress: false,
              thirdPartyVendor: "",
              adTrackingID: "",
              badges: {
                imageBased: [],
                textBased: [],
                textExtendedBadges: [],
              },
              lastMileTravelString: "6 kms",
              hasSurge: false,
              aggregatedDiscountInfoV3: {
                header: "₹125 OFF",
                subHeader: "ABOVE ₹249",
                discountTag: "FLAT DEAL",
                headerTypeV2: 0,
              },
              sla: {
                restaurantId: "534235",
                deliveryTime: 33,
                minDeliveryTime: 33,
                maxDeliveryTime: 33,
                lastMileTravel: 6.099999904632568,
                lastMileDistance: 0,
                serviceability: "SERVICEABLE",
                rainMode: "NONE",
                longDistance: "NOT_LONG_DISTANCE",
                preferentialService: false,
                iconType: "EMPTY",
              },
              promoted: false,
              avgRating: "4.5",
              totalRatings: 500,
              new: false,
            },
            subtype: "basic",
          },
        ],
        totalRestaurants: 1469,
      },
      subtype: "personalized",
    },
    parentWidget: false,
  },
];
